name: AWS Amazon Linux 2 3.14.2
on: [push]
jobs:
  build:
    runs-on: amazonlinux
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.14.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.14.2
    - name: Install dependencies
      run: |
        make install-amazon-linux
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Format
      run: |
        make format
